version: '3.8'

services:
  db:
    image: postgres:13
    container_name: job_board_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: job_board
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - jobboard_net

volumes:
  pg_data:
    driver: local

networks:
  jobboard_net:
    driver: bridge
